baseurl = "/"
languageCode = "ja-jp"
title = "Hugoサンプルサイト"
contentDir = "content"

[taxonomies]
tag = "tags"
author = "authors"

[permalinks]
articles = "/:title"
tags = "/:slug/"
authors = "/:slug/"
